name: 12 Saatte Bir Premier Ligi Güncelle

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Botu Çalıştır ve JSON Üret
        run: python bot.py

      - name: Değişiklikleri GitHub'a Yükle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git pull origin main --rebase
          git add matches.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Güncel Premier Lig Verileri"
          git push
